<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>in.sukruta.gdoc</groupId>
    <artifactId>gdoc</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <doesthiscompile.version>0.9.0</doesthiscompile.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>nl.firtree.doesthiscompile</groupId>
            <artifactId>swing-desktop</artifactId>
            <version>0.9.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit</artifactId>
            <version>6.9.0.202403050737-r</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>gdoc</finalName>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/generated-sources/</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            
            <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>3.2.5</version>
</plugin>
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>3.1.0</version>

    <configuration>
        <mainClass>in.sukruta.gdoc.clone_repo</mainClass>
    </configuration>
</plugin>


            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>write-version</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <loadresource property="packagePath">
                                    <propertyresource name="project.groupId"/>
                                    <filterchain>
                                        <tokenfilter>
                                            <replacestring from="." to="/"/>
                                        </tokenfilter>
                                    </filterchain>
                                </loadresource>
                                <echo file="${project.basedir}/src/main/generated-sources/${packagePath}/Version.java">
                                        package in.sukruta.gdoc;
public class Version {
   public static final String VERSION = "${project.version}";
   public static final String API_VERSION = "${doesthiscompile.version}";}
                                </echo>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>api</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>nl.firtree.doesthiscompile</groupId>
                    <artifactId>api</artifactId>
                    <version>${doesthiscompile.version}</version>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>standalone</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>nl.firtree.doesthiscompile</groupId>
                    <artifactId>engine</artifactId>
                    <version>${doesthiscompile.version}</version>
                </dependency>
                <!-- If you need polyglot support, uncomment the applicable dependencies below
                <dependency>
                    <groupId>nl.firtree.doesthiscompile</groupId>
                    <artifactId>python-runner</artifactId>
                    <version>${doesthiscompile.version}</version>
                </dependency>
                <dependency>
                    <groupId>nl.firtree.doesthiscompile</groupId>
                    <artifactId>javascript-runner</artifactId>
                    <version>${doesthiscompile.version}</version>
                </dependency>
                -->
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-shade-plugin</artifactId>
                        <version>3.6.0</version> <!-- Use the latest version -->
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>shade</goal>
                                </goals>
                                <configuration>
                                    <filters>
                                        <filter>
                                            <artifact>*:*</artifact>
                                            <excludes>
                                                <exclude>META-INF/*.SF</exclude>
                                                <exclude>META-INF/*.DSA</exclude>
                                                <exclude>META-INF/*.RSA</exclude>
                                            </excludes>
                                        </filter>
                                    </filters>
                                    <transformers>
                                        <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                        <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                            <mainClass>in.sukruta.gdoc.Main</mainClass>
                                            <manifestEntries>
                                                <Multi-Release>true</Multi-Release>
                                            </manifestEntries>
                                        </transformer>
                                    </transformers>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>

</project>
